name: food_delivery
description: "A new Flutter project."

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' 

# Versioning for the application
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  # Cupertino Icons for iOS-style icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Recommended lint rules for better coding practices
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Assets used in the application
  assets:
    - assets/images/craft-burger-wooden-cutting-board-brown-paper-classic-retro-burgers-creative-ai-design-background-instagram-facebook-325613753.webp
    - assets/images/empty-cart-512.webp
    - assets/images/sohila.png

  # Fonts used in the application
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans_Condensed-Italic.ttf
        - asset: assets/fonts/OpenSans_SemiCondensed-Regular.ttf
        - asset: assets/fonts/OpenSans-Italic.ttf
          weight: 700
